CREATE TABLE IF NOT EXISTS "nchb_team" (
	"id" serial PRIMARY KEY NOT NULL,
	"name" varchar(256) NOT NULL,
	"league" varchar(50) NOT NULL,
	"language" varchar(50) NOT NULL,
	"leader_name" varchar(256) NOT NULL,
	"leader_email" varchar(256) NOT NULL,
	"leader_phone" varchar(50) NOT NULL,
	"captain_name" varchar(256) NOT NULL,
	"captain_school" varchar(256) NOT NULL,
	"captain_grade" integer NOT NULL,
	"captain_email" varchar(256) NOT NULL,
	"captain_phone" varchar(50) NOT NULL,
	"member1_name" varchar(256) NOT NULL,
	"member1_school" varchar(256) NOT NULL,
	"member1_grade" integer NOT NULL,
	"member1_email" varchar(256) NOT NULL,
	"member1_phone" varchar(50) NOT NULL,
	"member2_name" varchar(256) NOT NULL,
	"member2_school" varchar(256) NOT NULL,
	"member2_grade" integer NOT NULL,
	"member2_email" varchar(256) NOT NULL,
	"member2_phone" varchar(50) NOT NULL,
	"member3_name" varchar(256),
	"member3_school" varchar(256),
	"member3_grade" integer,
	"member3_email" varchar(256),
	"member3_phone" varchar(50),
	"created_at" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp,
	CONSTRAINT "nchb_team_name_unique" UNIQUE("name"),
	CONSTRAINT "nchb_team_captain_email_unique" UNIQUE("captain_email")
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "team_idx" ON "nchb_team" ("name");